BaseUrl= "/"
LanguageCode= "en-US"
Title= "SchoolCoin"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2018"
canonifyurls = true

[author]
  name = "tgunz"

[params]
  description = "A clear path to the security & privacy of digital money"
  cover = "images/user.jpg"
  author = "syui"
  authorlocation = ""
  authorwebsite = "http://syui.github.io/hugo-theme-air"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
